version: '3'
services:
  mauve-dex:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev_package
    command: yarn dev
    environment:
      - NODE_ENV=local
    env_file:
      - ./.env.local
    ports:
      - 3000:3000
    volumes:
      - ./:/app/:z
      - /app/node_modules
      - ./tsconfig.json:/app/tsconfig.json:z
